// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7da91e770e514c8 "portfolite (copy)", do not edit manually */
"use client";
import {
  stdin_default
} from "../chunks/chunk-UBLLU2ZV.js";
import "../chunks/chunk-4NPMLM6U.js";

// virtual:elements/social-media
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "fz6QcpNXS": { "path": "/blog" }, "gSWbG5WG4": { "path": "/404" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "f7da91e770e514c8c53b897bc21d22b1cb70d52563dff3ae47cf007ba316fd39",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "fz6QcpNXS": {
          "path": "/blog"
        },
        "gSWbG5WG4": {
          "path": "/404"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "f7da91e770e514c8c53b897bc21d22b1cb70d52563dff3ae47cf007ba316fd39",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
