// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7da91e770e514c8 "portfolite (copy)", do not edit manually */
"use client";

// virtual:menu-icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ahhaRWKBSa7GC20odGzU/Ip88Zg5NhiM0rUmgir1r/MmHwaI6bc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["CPbzKAr6L", "JrHCHZ8vy"];
var serializationHash = "framer-CFeeQ";
var variantClassNames = { CPbzKAr6L: "framer-v-zh8s9o", JrHCHZ8vy: "framer-v-12pev7f" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { damping: 20, delay: 0, mass: 1, stiffness: 300, type: "spring" };
var radiusForCorner = (value, cornerIndex) => {
  if (typeof value === "number" && Number.isFinite(value)) return Math.max(0, value) + "px";
  if (typeof value !== "string" || typeof cornerIndex !== "number") return void 0;
  const segments = value.split(" ");
  return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Close: "JrHCHZ8vy", Hamburger: "CPbzKAr6L" };
var getProps = ({ height, id, radius, width, ...props }) => {
  return { ...props, d2WdKj7yR: radius ?? props.d2WdKj7yR, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "CPbzKAr6L" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, d2WdKj7yR, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "CPbzKAr6L", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTap1jed072 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("JrHCHZ8vy");
  });
  const onTap13q1h6c = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("CPbzKAr6L");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsxs(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-zh8s9o", className, classNames), "data-framer-name": "Hamburger", "data-highlight": true, layoutDependency, layoutId: "CPbzKAr6L", onTap: onTap1jed072, ref: refBinding, style: { ...style }, ...addPropertyOverrides({ JrHCHZ8vy: { "data-framer-name": "Close", onTap: onTap13q1h6c } }, baseVariant, gestureVariant), children: [/* @__PURE__ */ _jsx(motion.div, { className: "framer-bciays", layoutDependency, layoutId: "D8g0i2TPu", style: { backgroundColor: "var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))", borderBottomLeftRadius: radiusForCorner(d2WdKj7yR, 3), borderBottomRightRadius: radiusForCorner(d2WdKj7yR, 2), borderTopLeftRadius: radiusForCorner(d2WdKj7yR, 0), borderTopRightRadius: radiusForCorner(d2WdKj7yR, 1), rotate: 0 }, variants: { JrHCHZ8vy: { backgroundColor: "rgb(255, 255, 255)", rotate: 45 } } }), /* @__PURE__ */ _jsx(motion.div, { className: "framer-8e3nfd", layoutDependency, layoutId: "S4N9rAXvt", style: { backgroundColor: "var(--token-7a7ce709-7970-4e23-97d8-1ae0355d02f0, rgb(255, 255, 255))", borderBottomLeftRadius: radiusForCorner(d2WdKj7yR, 3), borderBottomRightRadius: radiusForCorner(d2WdKj7yR, 2), borderTopLeftRadius: radiusForCorner(d2WdKj7yR, 0), borderTopRightRadius: radiusForCorner(d2WdKj7yR, 1), rotate: 0 }, variants: { JrHCHZ8vy: { backgroundColor: "rgb(255, 255, 255)", rotate: -45 } } })] }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-CFeeQ.framer-nebkpz, .framer-CFeeQ .framer-nebkpz { display: block; }", ".framer-CFeeQ.framer-zh8s9o { cursor: pointer; height: 30px; overflow: hidden; position: relative; width: 30px; }", ".framer-CFeeQ .framer-bciays { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: visible; position: absolute; top: 10px; width: 20px; }", ".framer-CFeeQ .framer-8e3nfd { bottom: 10px; flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: visible; position: absolute; width: 20px; }", ".framer-CFeeQ.framer-v-12pev7f.framer-zh8s9o { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 30px); }", ".framer-CFeeQ.framer-v-12pev7f .framer-bciays { top: calc(50.00000000000002% - 2px / 2); }", ".framer-CFeeQ.framer-v-12pev7f .framer-8e3nfd { bottom: unset; top: calc(50.00000000000002% - 2px / 2); }"];
var FramerMmHwaI6bc = withCSS(Component, css, "framer-CFeeQ");
var stdin_default = FramerMmHwaI6bc;
FramerMmHwaI6bc.displayName = "Menu Icon";
FramerMmHwaI6bc.defaultProps = { height: 30, width: 30 };
addPropertyControls(FramerMmHwaI6bc, { variant: { options: ["CPbzKAr6L", "JrHCHZ8vy"], optionTitles: ["Hamburger", "Close"], title: "Variant", type: ControlType.Enum }, d2WdKj7yR: { defaultValue: 0, displayStepper: true, max: 1, min: 0, title: "Radius", type: ControlType.Number } });
addFonts(FramerMmHwaI6bc, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:menu-icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "CPbzKAr6L"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "fz6QcpNXS": { "path": "/blog" }, "gSWbG5WG4": { "path": "/404" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "f7da91e770e514c8c53b897bc21d22b1cb70d52563dff3ae47cf007ba316fd39",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "fz6QcpNXS": {
          "path": "/blog"
        },
        "gSWbG5WG4": {
          "path": "/404"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "f7da91e770e514c8c53b897bc21d22b1cb70d52563dff3ae47cf007ba316fd39",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
